### ISSUE TITLE
Induccion matematica

### ISSUE THREAD

**Issue by Alondra-oss** [SistemasTecTlaxiaco/actividad-9-practica-de-inducci-n-matem-tica-team-sael-1as#1]
[induccion matematica,..pdf](https://github.com/user-attachments/files/17529123/induccion.matematica.pdf)

**Comment by Eddi3mendoz** [comment]
Portada:25/25
Procedimiento:20/25
Figuras, Ilustraciones y Fotografías:18/25
Resultados y conclusiones:24/25
Calificación: 17.4/20

**Comment by josealfredo79** [comment]
bien hecho y revisado...
